#testroute
GEt http://localhost:3000/api/v1/

###
#Login route
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "userName" : "Amil P A",
  "password" : "neeyetha"
}

###
#Dashboard route
GET http://localhost:3000/api/v1/dashboard